-- Spring Session JDBC's own schema (vendored verbatim from
-- spring-session-jdbc 4.0.3's schema-sqlite.sql). The SCREAMING_CASE naming
-- breaks from the rest of this project's snake_case DDL because these tables
-- and columns are read/written by the framework's fixed SQL, not ours to
-- rename.

CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHARACTER(36) NOT NULL,
	SESSION_ID CHARACTER(36) NOT NULL,
	CREATION_TIME INTEGER NOT NULL,
	LAST_ACCESS_TIME INTEGER NOT NULL,
	MAX_INACTIVE_INTERVAL INTEGER NOT NULL,
	EXPIRY_TIME INTEGER NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
